//
// Created by zjcszn on 2023/8/10.
//

#ifndef USB_DEMO_MIDDLEWARE_CHERRYUSB_USER_CHERRYUSB_DEMO_H_
#define USB_DEMO_MIDDLEWARE_CHERRYUSB_USER_CHERRYUSB_DEMO_H_

#define CHERRYUSB_USBD_DEMO 1

void cdc_acm_msc_init(void);

#endif //USB_DEMO_MIDDLEWARE_CHERRYUSB_USER_CHERRYUSB_DEMO_H_
