/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.0.0.0                                               */
/*  Date (dd.mm.yyyy):  7. 7.2020   Time (hh:mm): 10:44                        */
/*******************************************************************************/


#ifndef _GUIAPP_DISPLAY_1_RESOURCES_H_
#define _GUIAPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

#if !defined(GX_UTF8_SUPPORT)
#error "The symbol GX_UTF8_SUPPORT must be defined to support the Studio project settings".
#endif

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 800
#define DISPLAY_1_Y_RESOLUTION 480
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_CHINESE 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define DISPLAY_1_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define GX_FONT_ID_NEWFONT 4
#define DISPLAY_1_FONT_TABLE_SIZE 5

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_ARMFLYLOGO 5
#define GX_PIXELMAP_ID_ROUND_EDGE_SMALL 6
#define GX_PIXELMAP_ID_ROUND_EDGE_SMALL_PRESSED 7
#define GX_PIXELMAP_ID_ROUND_ICON_BUTTON 8
#define GX_PIXELMAP_ID_ROUND_ICON_BUTTON_PRESSED 9
#define GX_PIXELMAP_ID_TOGGLE_ROUND_SMALL_BUTTON_OFF 10
#define GX_PIXELMAP_ID_TOGGLE_ROUND_SMALL_BUTTON_ON 11
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 12

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define DISPLAY_1_STRING_TABLE_SIZE 3

#endif                                       /* sentry                         */
